sudo: required
services
- docker
language: python
python:
- "3.8.0"
install:
- pip install -r requirements.txt
# command to run tests
script:
# unit test
- python -m unittest -v
after_success:
- sh .travis/deploy_dockerhub.sh