# sudo: required
# services:
#     - docker
language: python
python:
    - "3.8.0"
install:
    - pip install -r requirements.txt
# command to run tests
script:
# unit test
    - python -m unittest -v
deploy:
    provider: heroku
    api_key: $HEROKU_API_KEY
    app: dante-bk-hub
    on:
        repo: pat64j/dante-backend
# after_success:
#     - sh .travis/deploy__dockerhub.sh
#     – test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy__heroku.sh
