"""add updated_at column to token_blacklist table

Revision ID: 0dbc42ae52bd
Revises: 864ddbb2c652
Create Date: 2020-08-03 11:56:10.746679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbc42ae52bd'
down_revision = '864ddbb2c652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_blacklist', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_blacklist', 'updated_at')
    # ### end Alembic commands ###
