"""rename groups property on User model

Revision ID: 146e6a5b9825
Revises: 498df0b4c3e0
Create Date: 2020-07-13 14:01:13.075275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '146e6a5b9825'
down_revision = '498df0b4c3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'creator_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'creator_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
