"""add category, message_type and message table

Revision ID: 27ce67ba5f4d
Revises: 0dbc42ae52bd
Create Date: 2020-08-04 20:40:09.626568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ce67ba5f4d'
down_revision = '0dbc42ae52bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_name', sa.String(length=50), nullable=False),
    sa.Column('c_descripton', sa.String(length=100), nullable=True),
    sa.Column('c_thumbnail', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t_name', sa.String(length=50), nullable=False),
    sa.Column('t_description', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('m_title', sa.String(length=100), nullable=True),
    sa.Column('m_description', sa.String(length=200), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('m_thumbnail', sa.String(length=100), nullable=True),
    sa.Column('m_link', sa.String(length=200), nullable=True),
    sa.Column('m_duration', sa.String(length=50), nullable=True),
    sa.Column('m_broadcast', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['message_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages_categories',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('message_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages_categories')
    op.drop_table('messages')
    op.drop_table('message_types')
    op.drop_table('categories')
    # ### end Alembic commands ###
