"""add date of birth column on users table

Revision ID: 45e03fc0e023
Revises: 8e35b717e272
Create Date: 2020-07-30 19:16:31.408578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e03fc0e023'
down_revision = '8e35b717e272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bday', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bday')
    # ### end Alembic commands ###
