"""add created_at field to blacklist table

Revision ID: 8e35b717e272
Revises: 3caad03e76ac
Create Date: 2020-07-19 19:30:37.841913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e35b717e272'
down_revision = '3caad03e76ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_blacklist', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_blacklist', 'created_at')
    # ### end Alembic commands ###
