"""fix description column naming for categories table

Revision ID: e32982ca9daa
Revises: 27ce67ba5f4d
Create Date: 2020-08-07 16:25:32.465169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e32982ca9daa'
down_revision = '27ce67ba5f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('c_description', sa.String(length=100), nullable=True))
    op.drop_column('categories', 'c_descripton')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('c_descripton', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('categories', 'c_description')
    # ### end Alembic commands ###
